//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./BinaryUpload_types');
//HELPER FUNCTIONS AND STRUCTURES

BinaryUpload_upload_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    }
  }
};
BinaryUpload_upload_args.prototype = {};
BinaryUpload_upload_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.BinaryUploadRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BinaryUpload_upload_args.prototype.write = function(output) {
  output.writeStructBegin('BinaryUpload_upload_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BinaryUpload_upload_result = function(args) {
};
BinaryUpload_upload_result.prototype = {};
BinaryUpload_upload_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BinaryUpload_upload_result.prototype.write = function(output) {
  output.writeStructBegin('BinaryUpload_upload_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

BinaryUploadClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
BinaryUploadClient.prototype = {};
BinaryUploadClient.prototype.upload = function(request, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_upload(request);
};

BinaryUploadClient.prototype.send_upload = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('upload', Thrift.MessageType.CALL, this.seqid);
  var args = new BinaryUpload_upload_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BinaryUploadClient.prototype.recv_upload = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BinaryUpload_upload_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
BinaryUploadProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
BinaryUploadProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

BinaryUploadProcessor.prototype.process_upload = function(seqid, input, output) {
  var args = new BinaryUpload_upload_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.upload(args.request, function (err, result) {
    var result = new BinaryUpload_upload_result((err != null ? err : {success: result}));
    output.writeMessageBegin("upload", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

