//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = module.exports = {};
BinaryUploadRequest = module.exports.BinaryUploadRequest = function(args) {
  this.id = null;
  this.blob = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
    if (args.blob !== undefined) {
      this.blob = args.blob;
    }
  }
};
BinaryUploadRequest.prototype = {};
BinaryUploadRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.blob = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BinaryUploadRequest.prototype.write = function(output) {
  output.writeStructBegin('BinaryUploadRequest');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.blob !== null && this.blob !== undefined) {
    output.writeFieldBegin('blob', Thrift.Type.STRING, 2);
    output.writeString(this.blob);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

