/**
 * Generated by Scrooge
 *   version: 3.16.1
 *   rev: 5121dbb0c9be44a53567dfa52592a7dc017853f8
 *   built at: 20140625-213527
 */
package pl.binary.thrift

import com.twitter.scrooge.{
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object BinaryUploadRequest extends ThriftStructCodec3[BinaryUploadRequest] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("BinaryUploadRequest")
  val IdField = new TField("id", TType.STRING, 1)
  val IdFieldManifest = implicitly[Manifest[String]]
  val BlobField = new TField("blob", TType.STRING, 2)
  val BlobFieldManifest = implicitly[Manifest[ByteBuffer]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      IdField,
      false,
      IdFieldManifest,
      None,
      None,
      immutable$Map(
      ),
      immutable$Map(
      )
    ),
    new ThriftStructFieldInfo(
      BlobField,
      false,
      BlobFieldManifest,
      None,
      None,
      immutable$Map(
      ),
      immutable$Map(
      )
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map[String, String](
    )

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: BinaryUploadRequest) {
  }

  override def encode(_item: BinaryUploadRequest, _oproto: TProtocol) {
    _item.write(_oproto)
  }

  override def decode(_iprot: TProtocol): BinaryUploadRequest = {
    var id: String = null
    var blob: ByteBuffer = null
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING => {
                id = readIdValue(_iprot)
              }
              case _actualType =>
                val _expectedType = TType.STRING
            
                throw new TProtocolException(
                  "Received wrong type for field 'id' (expected=%s, actual=%s).".format(
                    ttypeToHuman(_expectedType),
                    ttypeToHuman(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING => {
                blob = readBlobValue(_iprot)
              }
              case _actualType =>
                val _expectedType = TType.STRING
            
                throw new TProtocolException(
                  "Received wrong type for field 'blob' (expected=%s, actual=%s).".format(
                    ttypeToHuman(_expectedType),
                    ttypeToHuman(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      id,
      blob,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    id: String,
    blob: ByteBuffer
  ): BinaryUploadRequest =
    new Immutable(
      id,
      blob
    )

  def unapply(_item: BinaryUploadRequest): Option[scala.Product2[String, ByteBuffer]] = Some(_item)


  private def readIdValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  private def writeIdField(id_item: String, _oprot: TProtocol) {
    _oprot.writeFieldBegin(IdField)
    writeIdValue(id_item, _oprot)
    _oprot.writeFieldEnd()
  }

  private def writeIdValue(id_item: String, _oprot: TProtocol) {
    _oprot.writeString(id_item)
  }

  private def readBlobValue(_iprot: TProtocol): ByteBuffer = {
    _iprot.readBinary()
  }

  private def writeBlobField(blob_item: ByteBuffer, _oprot: TProtocol) {
    _oprot.writeFieldBegin(BlobField)
    writeBlobValue(blob_item, _oprot)
    _oprot.writeFieldEnd()
  }

  private def writeBlobValue(blob_item: ByteBuffer, _oprot: TProtocol) {
    _oprot.writeBinary(blob_item)
  }



  private def ttypeToHuman(byte: Byte) = {
    // from https://github.com/apache/thrift/blob/master/lib/java/src/org/apache/thrift/protocol/TType.java
    byte match {
      case TType.STOP   => "STOP"
      case TType.VOID   => "VOID"
      case TType.BOOL   => "BOOL"
      case TType.BYTE   => "BYTE"
      case TType.DOUBLE => "DOUBLE"
      case TType.I16    => "I16"
      case TType.I32    => "I32"
      case TType.I64    => "I64"
      case TType.STRING => "STRING"
      case TType.STRUCT => "STRUCT"
      case TType.MAP    => "MAP"
      case TType.SET    => "SET"
      case TType.LIST   => "LIST"
      case TType.ENUM   => "ENUM"
      case _            => "UNKNOWN"
    }
  }

  object Immutable extends ThriftStructCodec3[BinaryUploadRequest] {
    override def encode(_item: BinaryUploadRequest, _oproto: TProtocol) { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): BinaryUploadRequest = BinaryUploadRequest.decode(_iprot)
  }

  /**
   * The default read-only implementation of BinaryUploadRequest.  You typically should not need to
   * directly reference this class; instead, use the BinaryUploadRequest.apply method to construct
   * new instances.
   */
  class Immutable(
    val id: String,
    val blob: ByteBuffer,
    override val _passthroughFields: immutable$Map[Short, TFieldBlob]
  ) extends BinaryUploadRequest {
    def this(
      id: String,
      blob: ByteBuffer
    ) = this(
      id,
      blob,
      Map.empty
    )
  }

  /**
   * This Proxy trait allows you to extend the BinaryUploadRequest trait with additional state or
   * behavior and implement the read-only methods from BinaryUploadRequest using an underlying
   * instance.
   */
  trait Proxy extends BinaryUploadRequest {
    protected def _underlying_BinaryUploadRequest: BinaryUploadRequest
    override def id: String = _underlying_BinaryUploadRequest.id
    override def blob: ByteBuffer = _underlying_BinaryUploadRequest.blob
    override def _passthroughFields = _underlying_BinaryUploadRequest._passthroughFields
  }
}

trait BinaryUploadRequest
  extends ThriftStruct
  with scala.Product2[String, ByteBuffer]
  with java.io.Serializable
{
  import BinaryUploadRequest._

  def id: String
  def blob: ByteBuffer

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = id
  def _2 = blob

  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returend.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) orElse {
      val _fieldOpt: Option[TField] =
        _fieldId match {
          case 1 =>
            if (id ne null) {
              writeIdValue(id, _oprot)
              Some(BinaryUploadRequest.IdField)
            } else {
              None
            }
          case 2 =>
            if (blob ne null) {
              writeBlobValue(blob, _oprot)
              Some(BinaryUploadRequest.BlobField)
            } else {
              None
            }
          case _ => None
        }
      _fieldOpt match {
        case Some(_field) =>
          val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
          Some(TFieldBlob(_field, _data))
        case None =>
          None
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): BinaryUploadRequest = {
    var id: String = this.id
    var blob: ByteBuffer = this.blob
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        id = readIdValue(_blob.read)
      case 2 =>
        blob = readBlobValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      id,
      blob,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): BinaryUploadRequest = {
    var id: String = this.id
    var blob: ByteBuffer = this.blob

    _fieldId match {
      case 1 =>
        id = null
      case 2 =>
        blob = null
      case _ =>
    }
    new Immutable(
      id,
      blob,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetId: BinaryUploadRequest = unsetField(1)

  def unsetBlob: BinaryUploadRequest = unsetField(2)


  override def write(_oprot: TProtocol) {
    BinaryUploadRequest.validate(this)
    _oprot.writeStructBegin(Struct)
    if (id ne null) writeIdField(id, _oprot)
    if (blob ne null) writeBlobField(blob, _oprot)
    _passthroughFields.values foreach { _.write(_oprot) }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    id: String = this.id,
    blob: ByteBuffer = this.blob,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): BinaryUploadRequest =
    new Immutable(
      id,
      blob,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[BinaryUploadRequest]

  override def equals(other: Any): Boolean =
    _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[BinaryUploadRequest]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => this.id
    case 1 => this.blob
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "BinaryUploadRequest"
}